# Generated by Django 4.2 on 2024-05-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='numero_banos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
