# Generated by Django 4.2 on 2024-05-25 14:03

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_perfil_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='numero_hab',
            field=models.IntegerField(default=0, validators=[app.models.validate_min_value]),
        ),
    ]
