# Generated by Django 4.2 on 2024-05-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_inmueble_numero_hab'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='descripcion',
            field=models.TextField(default='Sin Descripcion'),
            preserve_default=False,
        ),
    ]
