# Generated by Django 4.2 on 2024-06-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='nombre_inmueble',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
